apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-matchLabels
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [present_verb]}
  template:
    metadata:
      name: presentverbnone
      labels:
        app: presentverb
    spec:
      containers:
      - name: present-verb-mysql
        image: emendez93/present_verb_mysql:0.1
        ports:
        - containerPort: 3306
      - name: present-verb-english-comando
        image: emendez93/present-verb-english-comando:0.3
        ports:
        - containerPort: 8080